// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC61a7jXqWAJNjsE-R2kEzWOqbxwEw6gk',
    appId: '1:286625784122:web:b187bc9cb6254e75107003',
    messagingSenderId: '286625784122',
    projectId: 'hustlesync-3c91f',
    authDomain: 'hustlesync-3c91f.firebaseapp.com',
    storageBucket: 'hustlesync-3c91f.firebasestorage.app',
    measurementId: 'G-BH06LMR0XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ09zJkV9fc26L7rdalA0UsTd5Z_AYVIM',
    appId: '1:286625784122:android:57872ff87c67100a107003',
    messagingSenderId: '286625784122',
    projectId: 'hustlesync-3c91f',
    storageBucket: 'hustlesync-3c91f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTyByzjXJxkFLBz4JkuLSiPvACVFAfhuQ',
    appId: '1:286625784122:ios:6e0df7eb5d220e37107003',
    messagingSenderId: '286625784122',
    projectId: 'hustlesync-3c91f',
    storageBucket: 'hustlesync-3c91f.firebasestorage.app',
    iosBundleId: 'com.example.hustlerSyn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTyByzjXJxkFLBz4JkuLSiPvACVFAfhuQ',
    appId: '1:286625784122:ios:6e0df7eb5d220e37107003',
    messagingSenderId: '286625784122',
    projectId: 'hustlesync-3c91f',
    storageBucket: 'hustlesync-3c91f.firebasestorage.app',
    iosBundleId: 'com.example.hustlerSyn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC61a7jXqWAJNjsE-R2kEzWOqbxwEw6gk',
    appId: '1:286625784122:web:325e1976482204d8107003',
    messagingSenderId: '286625784122',
    projectId: 'hustlesync-3c91f',
    authDomain: 'hustlesync-3c91f.firebaseapp.com',
    storageBucket: 'hustlesync-3c91f.firebasestorage.app',
    measurementId: 'G-GQ5REDV1VJ',
  );
}
